import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "./clientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ClientProvider>
          {children}
          {modal}
        </ClientProvider>
      </body>
    </html>
  );
}
